customhost = "employee.cpaymdnjm2bm.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "jordanngkentzu-employee"
customregion = "us-east-1"
